version: "3"

services:
  django_microuno:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    
  nginx:
    image: nginx:1.13
    ports:
      - 8100:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_microuno

volumes:
  .:
  static: